{% set version = "2.6.4" %}

package:
  name: flex
  version: {{ version }}

source:
  url: https://github.com/westes/flex/releases/download/v{{ version }}/flex-{{ version }}.tar.gz
  sha256: e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995

build:
  skip: true  # [win]
{% if bootstrapping == 'yes' %}
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  number: 1004
{% endif %}
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
{% if bootstrapping != 'yes' %}
    - libtool  # [unix]
    - automake
    - m4
{% endif %}
    - make      # [unix]
    - libiconv  # [not linux and not win]
    - help2man  # [not win]
  run:
    - libiconv  # [not linux and not win]
    - m4

test:
  commands:
    # CLI tests
    - flex --help

    # Include test
    - test -f ${PREFIX}/include/FlexLexer.h

    # Lib tests
    - test -f ${PREFIX}/lib/libfl.a
    - test -f ${PREFIX}/lib/libfl${SHLIB_EXT}  # [not win]

about:
  home: http://flex.sourceforge.net/
  license: BSD 2-Clause
  license_file: COPYING
  license_family: BSD
  summary: The Fast Lexical Analyzer

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
